import type { APIRoute } from 'astro';

/**
 * The sitemap, hand-built rather than generated by an integration.
 *
 * Five pages. A dependency whose whole job is to enumerate a list this short would be a supply
 * chain surface bought for nothing, and this repository sets a cooldown on new dependencies for
 * exactly that reason.
 *
 * The list is EXPLICIT and not derived from the filesystem. A glob over `src/pages` would quietly
 * publish anything anybody ever drops in there, which is how staging pages end up in an index.
 */
const PAGES = ['/', '/demo/', '/memory/', '/how-it-works/', '/status/'] as const;

export const GET: APIRoute = ({ site }) => {
  // `site` is configured from PUBLIC_SITE_URL and falls back to loopback. A sitemap full of
  // localhost URLs is useless but honest: it says this build was made locally, which is better
  // than inventing a production origin that may never exist.
  const origin = site ?? new URL('http://127.0.0.1:4321');
  const urls = PAGES.map((path) => `  <url><loc>${new URL(path, origin).href}</loc></url>`).join('\n');

  return new Response(
    `<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n${urls}\n</urlset>\n`,
    { headers: { 'Content-Type': 'application/xml; charset=utf-8' } },
  );
};
